version: "2"

services:

  mariadb:
    image: mariadb:10.1
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=phalcon
      - MYSQL_USER=phalcon
      - MYSQL_PASSWORD=phalcon

  client:
    image: amqamq/phalcon:nginx
    restart: always
    ports:
      - "1080:80"
    volumes:
      - ./client:/var/www/html

  server:
    image: amqamq/phalcon:nginx
    restart: always
    ports:
      - "2080:80"
    volumes:
      - ./server:/var/www/html

volumes:
  mysql:
    driver: local
