version: "2"

services:

  mariadb:
    image: mariadb:10.1
    restart: always
    command: |-
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4;'
    ports:
      - "13306:3306"
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - dev.env

  client:
    image: amqamq/phalcon:nginx
    restart: always
    ports:
      - "1080:80"
    volumes:
      - ./client:/app
      - ./client/docker/php-dev.ini:/usr/local/etc/php/php.ini
    env_file:
      - dev.env

  server:
    image: amqamq/phalcon:nginx
    restart: always
    ports:
      - "2080:80"
    volumes:
      - ./server:/app
      - ./server/docker/php-dev.ini:/usr/local/etc/php/php.ini
    env_file:
      - dev.env
    depends_on:
      - server-migration

  server-migration:
    image: amqamq/phalcon:nginx
    command: phalcon migration run
    volumes:
      - ./server:/app
      - ./server/docker/php-dev.ini:/usr/local/etc/php/php.ini
    env_file:
      - dev.env
    depends_on:
      - mariadb

volumes:
  mysql:
    driver: local
