version: "2"

services:

  mariadb:
    image: mariadb:10.1
    restart: always
    command: |-
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4;'
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - prod.env

  traefik:
    image: traefik
    container_name: traefik
    restart: always
    command: |-
      --logLevel=DEBUG
      --entrypoints='Name:http Address::80'
      --entrypoints='Name:https Address::443 TLS'
      --web
      --docker
      --docker.exposedbydefault=false
      --acme
      --acme.entrypoint=https
      --acme.email=amq@users.noreply.github.com
      --acme.storage=/acme/acme.json
      --acme.ondemand=false
      --acme.onhostrule=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /dev/null:/traefik.toml
      - acme:/acme

  client:
    build: ./client
    image: amqamq/sam101:client
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.backend=client"
      - "traefik.frontend.rule=Host:client.sam101.amq.space"
      - "traefik.frontend.entryPoints=http,https"
    env_file:
      - prod.env

  server:
    build: ./server
    image: amqamq/sam101:server
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.backend=server"
      - "traefik.frontend.rule=Host:server.sam101.amq.space"
      - "traefik.frontend.entryPoints=http,https"
    env_file:
      - prod.env
    depends_on:
      - server-migration

  server-migration:
    build: ./server
    image: amqamq/sam101:server
    command: bash -c "sleep 20 && phalcon migration run"
    env_file:
      - prod.env
    depends_on:
      - mariadb

  # optional
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --interval 30

  # optional
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.sam101.amq.space"
      - "traefik.frontend.entryPoints=http,https"

volumes:
  mysql:
    driver: local
  acme:
    driver: local
  portainer:
    driver: local
