version: "2"

services:

  mariadb:
    image: mariadb:10.1
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - .env

  client:
    image: amqamq/phalcon:nginx
    restart: always
    ports:
      - "1080:80"
    volumes:
      - ./client:/app
      - ./client/docker/php-dev.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env

  server:
    image: amqamq/phalcon:nginx
    restart: always
    ports:
      - "2080:80"
    volumes:
      - ./server:/app
      - ./server/docker/php-dev.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env

volumes:
  mysql:
    driver: local
