version: "2"

services:

  mariadb:
    image: mariadb:10.1
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - prod.env

  client:
    build: ./client
    image: amqamq/sam101:client
    restart: always
    environment:
      - VIRTUAL_HOST=client.sam101.amq.space
      - LETSENCRYPT_HOST=client.sam101.amq.space
      - LETSENCRYPT_EMAIL=amq@users.noreply.github.com
    env_file:
      - prod.env

  server:
    build: ./server
    image: amqamq/sam101:server
    restart: always
    environment:
      - VIRTUAL_HOST=server.sam101.amq.space
      - LETSENCRYPT_HOST=server.sam101.amq.space
      - LETSENCRYPT_EMAIL=amq@users.noreply.github.com
    env_file:
      - prod.env

  server-migration:
    build: ./server
    image: amqamq/sam101:server
    command: phalcon migration run
    env_file:
      - prod.env
    depends_on:
      - mariadb

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - certs:/etc/nginx/certs

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # optional
  gc:
    image: spotify/docker-gc
    container_name: gc
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # optional
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --interval 30

  # optional
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    environment:
      - VIRTUAL_PORT=9000
      - VIRTUAL_HOST=portainer.sam101.amq.space
      - LETSENCRYPT_HOST=portainer.sam101.amq.space
      - LETSENCRYPT_EMAIL=amq@users.noreply.github.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer:/data

volumes:
  mysql:
    driver: local
  certs:
    driver: local
  portainer:
    driver: local
