<?php
/**
 * Created by PhpStorm.
 * User: www-data
 * Date: 29.03.17
 * Time: 12:26
 */

namespace Sam\Client\Controllers;


use Sam\Client\Models\User;
use Sam\Client\Plugins\RestPlugin;

class DashboardController extends ControllerBase
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction() {

        $this->view->user = $this->session->get("auth");
    }

    public function customerAction($loginName = false) {
        /**
         * @var $user User
         */
        $user = $this->session->get("auth");
        /**
         * @var $server RestPlugin
         */
        $server = $this->getDI()->get("server");

        if($this->request->isGet()) {
            $search = $this->request->get("search");
            $depot = $this->request->get("depot");
            $stock = $this->request->get("stock");
            $new = $this->request->get("new");

            if($loginName === false) {
                /*
                 *  Shows all Customers
                 */
                $customers = $server->getCustomers();
                $this->view->customers = $customers;
            } else if($loginName !== false && !isset($search) && !isset($depot)) {
                /*
                 * shows a single customer
                 */
                $customer = $server->getCustomer($loginName);
                $this->view->customer = $customer;
            } else if($loginName !== false && isset($search)) {
                /*
                 * searches for customers and views the list
                 */
                $customers = $server->findCustomers($search);
                $this->view->customers = $customers;
            } else if($loginName !== false && isset($depot) && empty($depot) && isset($new) && empty($new)) {

                $customer = $server->getCustomer($loginName);
                $this->view->newDepot = true;
                $this->view->customer = $customer;
            } else if($loginName !== false && isset($depot) && !isset($stock)) {
                $depot = $server->getDepot($depot, $loginName);
                $this->view->depot = $depot;
            } else if($loginName !== false && isset($depot) && isset($stock) && empty($stock) ) {
                $depot = $server->getDepot($depot, $loginName);
                $this->view->depot = $depot;
                $this->view->searchStocks = true;
            } else if($loginName !== false && isset($depot) && isset($stock) && !empty($stock) ) {
                $depot = $server->getDepot($depot, $loginName);
                $this->view->depot = $depot;
                $this->view->searchStocks = true;

                $stocks = $server->getStocks($stock);
                $this->view->stocks = $stocks;
            }
        } else if($this->request->isPost()) {
            $newDepot = $this->request->getPost("newDepot");
            if(empty($newDepot)) {
                $depot = $this->request->getPost("depot", null, null, true);
                $direction = $this->request->getPost("direction", null, null, true);
                $shares = $this->request->getPost("shares", null, null, true);
                $symbol = $this->request->getPost("symbol", null, null, true);
                $transaction = false;
                if($direction === "buy") {
                    $transaction = $server->buyStock($shares, $symbol, $depot);
                } else if($direction === "sell") {
                    $transaction = $server->sellStock($shares, $symbol, $depot);
                }
                $this->view->transaction = $transaction;
            } else {
                $budget = $this->request->getPost("budget");
                $depot = $server->addDepot($loginName, $budget);
                $this->view->depot = $depot;
            }


        }
    }

    public function addCustomerAction() {
        if($this->request->isGet()) {

        } else if($this->request->isPost()) {
            $loginName = $this->request->getPost("loginName");
            $password = $this->request->getPost("password");
            $firstname = $this->request->getPost("firstname");
            $lastname = $this->request->getPost("lastname");
            $address = $this->request->getPost("address");
            $phone = $this->request->getPost("phone");

            if(!empty($loginName) && !empty($password) && !empty($firstname) && !empty($lastname) && !empty($address)) {
                /** @var RestPlugin $server */
                $server = $this->di->get("server");
                $res = $server->addCustomer($loginName, $password, $firstname, $lastname, $phone, $address);
                if(isset($res->success)) {
                    $this->dispatcher->forward(array(
                        "controller" => "dashboard",
                        "action" => "index"
                    ));
                    return;
                }
            }
        }
    }
}