<?php
namespace Sam\Client\Controllers;

/**
 * Created by PhpStorm.
 * User: www-data
 * Date: 12.03.17
 * Time: 11:07
 */
class ErrorController extends ControllerBase
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


    public function show404Action() {
        $var = 1;
    }

    public function show401Action() {
        $var = 1;
    }

    public function show500Action() {
        $var = 1;

    }

}