<?php
namespace Sam\Server\Controllers;

use Sam\Server\Models\Bank;
use Sam\Server\Plugins\AuthenticationPlugin;

/**
 * Created by PhpStorm.
 * User: www-data
 * Date: 24.03.17
 * Time: 09:45
 */
class BankController extends ControllerBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function getAction()
    {
        $auth = $this->session->get("auth");
        if (AuthenticationPlugin::isAllowedEmployee($auth, $auth["user"]->User->getBankId(), $this->di->get("config"))) {
            return json_encode(Bank::findFirst(array("id = :id:", "bind" => array("id" => $auth["user"]->User->getBankId()))));
        } else {
            return json_encode(array("error" => "request error", "code" => "70"));
        }
    }
}
