<?php
namespace Sam\Server\Controllers;

/**
 * Created by PhpStorm.
 * User: www-data
 * Date: 24.03.17
 * Time: 09:46
 */
class EmployeeController extends ControllerBase
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function getAction($id) {

    }

    public function postAction() {

    }
}