<?php
namespace Sam\Server\Controllers;

use Sam\Server\Models\Transaction;
use Sam\Server\Models\Customer;
use Sam\Server\Models\User;
use Sam\Server\Plugins\AuthenticationPlugin;

/**
 * Created by PhpStorm.
 * User: www-data
 * Date: 24.03.17
 * Time: 09:47
 */
class TransactionController extends ControllerBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}
